services:
  logbot:
    build:
      dockerfile: ./docker/development/logbot/Dockerfile
    volumes:
      - ./:/go/src/github.com/chistyakoviv/logbot
    ports:
      - 80:80 # bot webhook
      - 6060:6060 # pprof metrics
    environment:
      CONFIG_PATH: config/local.yaml

  logbot-pg:
    image: postgres:17.6-alpine3.22
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-cli:
    build:
      dockerfile: ./docker/development/go-cli/Dockerfile
    volumes:
      - ./:/go/src/github.com/chistyakoviv/logbot
    environment:
      - PG_DSN=postgres://app:secret@logbot-pg/app?sslmode=disable
      - GOOSE_MIGRATION_DIR=./migrations
